modLoader="javafml" #mandatory
loaderVersion="${loader_version_range}" #mandatory

license="${mod_license}"
issueTrackerURL="https://github.com/lucaargolo/charta/issues" #optional

[[mods]] #mandatory
modId="${mod_id}" #mandatory
version="${mod_version}" #mandatory
displayName="${mod_name}" #mandatory
#updateJSONURL="https://change.me.example.invalid/updates.json" #optional
#displayURL="https://change.me.to.your.mods.homepage.example.invalid/" #optional
logoFile="icon.png"
#credits="" #optional
authors="${mod_authors}" #optional
description='''${mod_description}'''

[[mixins]]
config="${mod_id}.mixins.json"

[[accessTransformers]]
file="META-INF/accesstransformer.cfg"

[[dependencies.${mod_id}]] #optional
    modId="forge" #mandatory
    mandatory = true
    versionRange="${forge_version_range}" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory = true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"